spring.application.name=system
spring.datasource.url=jdbc:postgresql://localhost:5432/systemdb
spring.datasource.username=postgres
spring.datasource.password=Prosper1.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
